/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.devillsroom.poker.client;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Suit implements org.apache.thrift.TEnum {
  Hearts(0),
  Diamonds(1),
  Spades(2),
  Clubs(3);

  private final int value;

  private Suit(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Suit findByValue(int value) { 
    switch (value) {
      case 0:
        return Hearts;
      case 1:
        return Diamonds;
      case 2:
        return Spades;
      case 3:
        return Clubs;
      default:
        return null;
    }
  }
}
