/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace API
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class BetLimits : TBase
  {
    private long _to_call;
    private long _minimum_raise;

    public long To_call
    {
      get
      {
        return _to_call;
      }
      set
      {
        __isset.to_call = true;
        this._to_call = value;
      }
    }

    public long Minimum_raise
    {
      get
      {
        return _minimum_raise;
      }
      set
      {
        __isset.minimum_raise = true;
        this._minimum_raise = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool to_call;
      public bool minimum_raise;
    }

    public BetLimits() {
    }

    public void Read (TProtocol iprot)
    {
      TField field;
      iprot.ReadStructBegin();
      while (true)
      {
        field = iprot.ReadFieldBegin();
        if (field.Type == TType.Stop) { 
          break;
        }
        switch (field.ID)
        {
          case 1:
            if (field.Type == TType.I64) {
              To_call = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          case 2:
            if (field.Type == TType.I64) {
              Minimum_raise = iprot.ReadI64();
            } else { 
              TProtocolUtil.Skip(iprot, field.Type);
            }
            break;
          default: 
            TProtocolUtil.Skip(iprot, field.Type);
            break;
        }
        iprot.ReadFieldEnd();
      }
      iprot.ReadStructEnd();
    }

    public void Write(TProtocol oprot) {
      TStruct struc = new TStruct("BetLimits");
      oprot.WriteStructBegin(struc);
      TField field = new TField();
      if (__isset.to_call) {
        field.Name = "to_call";
        field.Type = TType.I64;
        field.ID = 1;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(To_call);
        oprot.WriteFieldEnd();
      }
      if (__isset.minimum_raise) {
        field.Name = "minimum_raise";
        field.Type = TType.I64;
        field.ID = 2;
        oprot.WriteFieldBegin(field);
        oprot.WriteI64(Minimum_raise);
        oprot.WriteFieldEnd();
      }
      oprot.WriteFieldStop();
      oprot.WriteStructEnd();
    }

    public override string ToString() {
      StringBuilder sb = new StringBuilder("BetLimits(");
      sb.Append("To_call: ");
      sb.Append(To_call);
      sb.Append(",Minimum_raise: ");
      sb.Append(Minimum_raise);
      sb.Append(")");
      return sb.ToString();
    }

  }

}
