/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

namespace API
{
  public enum BetType
  {
    Fold = 0,
    Check = 1,
    Call = 2,
    Blind = 3,
    Raise = 4,
    Allin = 5,
  }
}
