/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "player_strategy_constants.h"



const player_strategyConstants g_player_strategy_constants;

player_strategyConstants::player_strategyConstants() {
}



