/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef player_strategy_CONSTANTS_H
#define player_strategy_CONSTANTS_H

#include "player_strategy_types.h"



class player_strategyConstants {
 public:
  player_strategyConstants();

};

extern const player_strategyConstants g_player_strategy_constants;



#endif
