/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ranking_CONSTANTS_H
#define ranking_CONSTANTS_H

#include "ranking_types.h"



class rankingConstants {
 public:
  rankingConstants();

};

extern const rankingConstants g_ranking_constants;



#endif
