/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "ranking_constants.h"



const rankingConstants g_ranking_constants;

rankingConstants::rankingConstants() {
}



