/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "types_constants.h"

namespace API {

const typesConstants g_types_constants;

typesConstants::typesConstants() {
}

} // namespace

