%%
%% Autogenerated by Thrift Compiler (0.9.1)
%%
%% DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
%%

-module(types_types).

-include("types_types.hrl").

-export([struct_info/1, struct_info_ext/1]).

struct_info('competitor') ->
  {struct, [{1, string},
          {2, i64}]}
;

struct_info('card') ->
  {struct, [{1, i16},
          {2, i32},
          {3, string}]}
;

struct_info('bet') ->
  {struct, [{1, i64},
          {2, i32},
          {3, i64}]}
;

struct_info('betLimits') ->
  {struct, [{1, i64},
          {2, i64}]}
;

struct_info('handDescriptor') ->
  {struct, [{1, string},
          {2, {list, i16}}]}
;

struct_info('i am a dummy struct') -> undefined.

struct_info_ext('competitor') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, i64, 'stack', undefined}]}
;

struct_info_ext('card') ->
  {struct, [{1, undefined, i16, 'value', undefined},
          {2, undefined, i32, 'suit', undefined},
          {3, undefined, string, 'name', undefined}]}
;

struct_info_ext('bet') ->
  {struct, [{1, undefined, i64, 'amount', undefined},
          {2, undefined, i32, 'type', undefined},
          {3, undefined, i64, 'new_pot_size', undefined}]}
;

struct_info_ext('betLimits') ->
  {struct, [{1, undefined, i64, 'to_call', undefined},
          {2, undefined, i64, 'minimum_raise', undefined}]}
;

struct_info_ext('handDescriptor') ->
  {struct, [{1, undefined, string, 'name', undefined},
          {2, undefined, {list, i16}, 'ranks', []}]}
;

struct_info_ext('i am a dummy struct') -> undefined.

