/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.devillsroom.poker.client;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum BetType implements org.apache.thrift.TEnum {
  Fold(0),
  Check(1),
  Call(2),
  Blind(3),
  Raise(4),
  Allin(5);

  private final int value;

  private BetType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static BetType findByValue(int value) { 
    switch (value) {
      case 0:
        return Fold;
      case 1:
        return Check;
      case 2:
        return Call;
      case 3:
        return Blind;
      case 4:
        return Raise;
      case 5:
        return Allin;
      default:
        return null;
    }
  }
}
