#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'player_types'

module Player
  class Client
    include ::Thrift::Client

    def new_game()
      send_new_game()
      recv_new_game()
    end

    def send_new_game()
      send_message('new_game', New_game_args)
    end

    def recv_new_game()
      result = receive_message(New_game_result)
      return
    end

  end

  class Processor
    include ::Thrift::Processor

    def process_new_game(seqid, iprot, oprot)
      args = read_args(iprot, New_game_args)
      result = New_game_result.new()
      @handler.new_game()
      write_result(result, oprot, 'new_game', seqid)
    end

  end

  # HELPER FUNCTIONS AND STRUCTURES

  class New_game_args
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class New_game_result
    include ::Thrift::Struct, ::Thrift::Struct_Union

    FIELDS = {

    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end

